### PR TITLE
Add forms

### PR DESCRIPTION
**Pull request by tiagomarin**
### :heavy_check_mark: Create a method called `current_user` in your ApplicationController to make current user data available to all controllers.
-  It will return the first user from the database.
-  Don't worry about proper authentication at this time. You will add it in the upcoming projects.
 
### :heavy_check_mark: Create forms to perform the following functions:
- Creates a Post on behalf of the `current_user` (use the method that you created in your ApplicationController).
- Create a comment on behalf of the `current_user` (use the method that you created in your ApplicationController).

### :speech_balloon: Feel free to shoot me a message in the pull request if you have any questions.

Thank you for your time!

### CODE REVIEW

**Review by danmainah — APPROVED** [review]
Hi @tiagomarin , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tiagomarin** [comment]
Thank you for reviewing my code! 🙏

**Comment by danmainah** [comment]
Hi @tiagomarin , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses the old readme format kindly update your readme using[ this template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by GzimAsani — COMMENTED** [review]
Hi @tiagomarin , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses an old Readme template. I understand that your project was approved on November 2022 when we were using another Readme template. But now we have a new [README template](https://github.com/microverseinc/readme-template) so please update your current one with the new one and then you should be good to go 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rloterh — COMMENTED** [review]
## Status: Approved :heavy_check_mark:

Hi Tiago,  

Your project is complete!🏁 There is nothing else to say other than... it's time to merge it. Congratulations!  🎉

Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
