### PR TITLE
Autorization cancancan

### PR DESCRIPTION
**Pull request by tiagomarin**
### :heavy_check_mark: - A user can delete a post if it is theirs or if they have an admin role (column `role` has value `"admin"`). Used CanCanCan for this authorization.
- Implemented the post deleting functionality. Added the "Delete" button to the view and made sure that only authorized users can see it.

### :heavy_check_mark: - A user can delete a comment if it is theirs or if they have an admin role (column `role` has value `"admin"`). Used CanCanCan for this authorization.
- Implemented the comment deleting functionality. Added the "Delete" button to the view and make sure that only authorized users can see it.

### :speech_balloon: Feel free to shoot me a message in the pull request if you have any questions.

Thank you for your time!

### CODE REVIEW

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Tiago,  

Your project is complete, great job! 🥇 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Authorization with Cancan properly implemented
- Good ReadMe

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] OPTIONAL
It will be a good idea to also create a  `user.admin?` method inside the _user_ model for setting a blog admin, which should be similar to:

```ruby
   def admin?
     role == 'admin' ? true : false
   end
```

**You can also consider:**
- I think you should change the header title _Authors_ to _Author_ in your ReadMe, as this project is worked on by a sole contributor. 
Implementing the above change(s) will make your ReadMe/ repository stand out even better 😉

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tiagomarin** [comment]
Hi @rloterh :wave: 

Thanks a lot for reviewing my code. 🙏

I'll change the Readme part to author, I didn't notice that! :heavy_check_mark: 

Happy coding! :smile:

**Comment by prolajumokeoni** [comment]
Hi @tiagomarin 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pair-programming project, that does not have commit from your partner and  does not have the updated microverse readme template,

Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme and reopen a new pr with commits from you and your partner for this milestone


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @tiagomarin 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pair-programming project, that does not have commit from your **current partner** ,  kindly reopen a new pr with commits from you and your partner for this milestone

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mikethreels — COMMENTED** [review]
Hi Team, 

As you mentioned in your note, student success already approved the way of working for you and your partner.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
